version: '3'

services:
  next-wasm:
    build:
      context: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default
volumes:
  node_modules:
